### ISSUE TITLE
python base_mot17.py occur error

### ISSUE THREAD

**Issue by wangtuo111** [FFI-no/Paper-base-visapp-2024#1]
Traceback (most recent call last):
  File "/home/wangtuo/Downloads/Multi-Object-Tracking/Paper-base-visapp-2024-main/base_mot17.py", line 123, in <module>
    run_stuff()
  File "/home/wangtuo/Downloads/Multi-Object-Tracking/Paper-base-visapp-2024-main/base_mot17.py", line 18, in run_stuff
    vo = read_vo('data/MOT17/vo.json')
  File "/home/wangtuo/Downloads/Multi-Object-Tracking/Paper-base-visapp-2024-main/utils.py", line 115, in read_vo
    vo = json.load(vo_file)
  File "/home/wangtuo/anaconda3/envs/TestYOLOX/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/wangtuo/anaconda3/envs/TestYOLOX/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/wangtuo/anaconda3/envs/TestYOLOX/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/wangtuo/anaconda3/envs/TestYOLOX/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by wangtuo111** [comment]
The contents of the file "data/MOT17/vo.json" are as follows
version https://git-lfs.github.com/spec/v1
oid sha256:4e0687a392b72896a769d0e521e0fbe9bf54b0b6a4a009b735d63c62f6502294
size 2724916
